# Generated by Django 4.2.13 on 2024-05-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="changed_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
